/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pullu
 */
public final class AddBooks extends javax.swing.JFrame {
    
   Connection con;
   PreparedStatement pst;
   javax.swing.table.DefaultTableModel model;
    /**
     * Creates new form AddBooks
     */
    public AddBooks() {
        initComponents();
        loadbook();
    }
    public void loadbook() {
       try {
            model=(javax.swing.table.DefaultTableModel)booktable.getModel();
           con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "scott", "tiger");
           Statement st=con.createStatement();
           model.setRowCount(0);
           ResultSet rs=st.executeQuery("select * from book");
           
           while(rs.next())
           {
               model.insertRow(model.getRowCount(),new Object[]{rs.getString(1),rs.getString(2),rs.getInt(3)});
           }  
       } catch (SQLException ex) {
           Logger.getLogger(AddBooks.class.getName()).log(Level.SEVERE, null, ex);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bookname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        author = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bookcount = new javax.swing.JTextField();
        addbookbt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        booktable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        homebt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        AddMembt = new javax.swing.JButton();
        AddBookbt = new javax.swing.JButton();
        BookDetailsbt = new javax.swing.JButton();
        IssueBookbt = new javax.swing.JButton();
        RetrunBookbt = new javax.swing.JButton();
        ShowDetailsbt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(255, 0, 0));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Book Name: ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Author:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("No. of Books: ");

        addbookbt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addbookbt.setText("Add Book");
        addbookbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbookbtActionPerformed(evt);
            }
        });

        booktable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Name", "Author", "No. of Books"
            }
        ));
        jScrollPane1.setViewportView(booktable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bookcount, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bookname, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(addbookbt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bookname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(bookcount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(addbookbt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(282, 282, 282))
        );

        jPanel3.setBackground(new java.awt.Color(102, 255, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/R.png"))); // NOI18N

        homebt.setText("Home");
        homebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(homebt)
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homebt)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        AddMembt.setText("Add Mem");
        AddMembt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMembtActionPerformed(evt);
            }
        });

        AddBookbt.setForeground(new java.awt.Color(204, 0, 0));
        AddBookbt.setText("Add Books");
        AddBookbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBookbtActionPerformed(evt);
            }
        });

        BookDetailsbt.setText("Book Details");
        BookDetailsbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookDetailsbtActionPerformed(evt);
            }
        });

        IssueBookbt.setText("Issue Book");
        IssueBookbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssueBookbtActionPerformed(evt);
            }
        });

        RetrunBookbt.setText("Return Book");
        RetrunBookbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetrunBookbtActionPerformed(evt);
            }
        });

        ShowDetailsbt.setText("Show Details");
        ShowDetailsbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowDetailsbtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowDetailsbt)
                    .addComponent(RetrunBookbt)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(IssueBookbt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddBookbt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddMembt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BookDetailsbt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(AddMembt)
                .addGap(26, 26, 26)
                .addComponent(AddBookbt)
                .addGap(34, 34, 34)
                .addComponent(BookDetailsbt)
                .addGap(34, 34, 34)
                .addComponent(IssueBookbt)
                .addGap(32, 32, 32)
                .addComponent(RetrunBookbt)
                .addGap(30, 30, 30)
                .addComponent(ShowDetailsbt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(210, 210, 210))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddMembtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMembtActionPerformed
        // TODO add your handling code here:
         AddMem am=new AddMem();
        am.setVisible(true);
    }//GEN-LAST:event_AddMembtActionPerformed

    private void AddBookbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBookbtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBookbtActionPerformed

    private void BookDetailsbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookDetailsbtActionPerformed
        // TODO add your handling code here:
         BookDetails bd=new BookDetails();
        bd.setVisible(true);
    }//GEN-LAST:event_BookDetailsbtActionPerformed

    private void IssueBookbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssueBookbtActionPerformed
        // TODO add your handling code here:
       IssueBook ib=new IssueBook();
         ib.setVisible(true);
    }//GEN-LAST:event_IssueBookbtActionPerformed

    private void RetrunBookbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetrunBookbtActionPerformed
        // TODO add your handling code here:
    ReturnBook rb=new ReturnBook();
            rb.setVisible(true);
    }//GEN-LAST:event_RetrunBookbtActionPerformed

    private void ShowDetailsbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowDetailsbtActionPerformed
        // TODO add your handling code here:
       ShowDetails sd=new ShowDetails();
         sd.setVisible(true);
    }//GEN-LAST:event_ShowDetailsbtActionPerformed

    private void homebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtActionPerformed
        // TODO add your handling code here:
       Main m=new Main();
        m.setVisible(true);
    }//GEN-LAST:event_homebtActionPerformed

    private void addbookbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbookbtActionPerformed
       try {
           // TODO add your handling code here:
           con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "scott", "tiger");
           Statement st=con.createStatement();
           model.setRowCount(0);
           ResultSet rs=st.executeQuery("select * from book");
           loadbook();
           
           int c=0;
           while(rs.next())
           {
               if(bookname.getText().equals(rs.getString(1)) && author.getText().equals(rs.getString(2)))
               {
                   c=1;
                   break;
               }
           }
           if(c==0)
           {
              pst=con.prepareStatement("insert into book values(?,?,?)");
              
              pst.setString(1,bookname.getText());
              pst.setString(2,author.getText());
              pst.setInt(3,Integer.valueOf(bookcount.getText()));
              pst.executeUpdate();
              model=(javax.swing.table.DefaultTableModel)booktable.getModel();
              model.insertRow(model.getRowCount(),new Object[]{bookname.getText(),author.getText(),Integer.valueOf(bookcount.getText())});
              
           }
           else
           {
              pst=con.prepareStatement("update book set bookcount=bookcount+? where bookname=? and author=?"); 
              pst.setInt(1,Integer.valueOf(bookcount.getText()));
              pst.setString(2,bookname.getText());
              pst.setString(3,author.getText());
              pst.executeUpdate();
            
              
              model=(javax.swing.table.DefaultTableModel)booktable.getModel();
              Statement st1=con.createStatement();
              ResultSet rs1=st1.executeQuery("select * from book");
              model.setRowCount(0);
              
              
              while(rs1.next())
              {
                  model.insertRow(model.getRowCount(),new Object[]{rs1.getString(1),rs1.getString(2),rs1.getInt(3)});
                  
                  
              }
              
           }
           JOptionPane.showMessageDialog(this,"Book Inserted Successfully");
           loadbook();
       } catch (SQLException ex) {
           Logger.getLogger(AddBooks.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_addbookbtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBookbt;
    private javax.swing.JButton AddMembt;
    private javax.swing.JButton BookDetailsbt;
    private javax.swing.JButton IssueBookbt;
    private javax.swing.JButton RetrunBookbt;
    private javax.swing.JButton ShowDetailsbt;
    private javax.swing.JButton addbookbt;
    private javax.swing.JTextField author;
    private javax.swing.JTextField bookcount;
    private javax.swing.JTextField bookname;
    private javax.swing.JTable booktable;
    private javax.swing.JButton homebt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private static class DefaultTableModel {

       
    }

   

    
   
}
