/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pullu
 */
public final class AddMem extends javax.swing.JFrame {
    Connection con;
    PreparedStatement pst;
    
 
    /**
     * Creates new form AddMem
     */
    public AddMem() {
        initComponents();
        Loadlibraryno();
    }
public void Loadlibraryno()
{
       
    libno.setEditable(false);
    libno.setText("VASAVI"+branchtype.getSelectedItem().toString()+"");
    
}   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        AddMembt = new javax.swing.JButton();
        AddBookbt = new javax.swing.JButton();
        BookDetailsbt = new javax.swing.JButton();
        IssueBookbt = new javax.swing.JButton();
        RetrunBookbt = new javax.swing.JButton();
        ShowDetailsbt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        libno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addbt = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        sno = new javax.swing.JTextField();
        empno = new javax.swing.JTextField();
        MemType = new javax.swing.JComboBox<>();
        branchtype = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        homebt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        AddMembt.setForeground(new java.awt.Color(255, 0, 0));
        AddMembt.setText("Add Mem");
        AddMembt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMembtActionPerformed(evt);
            }
        });

        AddBookbt.setText("Add Books");
        AddBookbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBookbtActionPerformed(evt);
            }
        });

        BookDetailsbt.setText("Book Details");
        BookDetailsbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookDetailsbtActionPerformed(evt);
            }
        });

        IssueBookbt.setText("Issue Book");
        IssueBookbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssueBookbtActionPerformed(evt);
            }
        });

        RetrunBookbt.setText("Return Book");
        RetrunBookbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetrunBookbtActionPerformed(evt);
            }
        });

        ShowDetailsbt.setText("Show Details");
        ShowDetailsbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowDetailsbtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowDetailsbt)
                    .addComponent(RetrunBookbt)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(IssueBookbt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddBookbt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddMembt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BookDetailsbt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(AddMembt)
                .addGap(26, 26, 26)
                .addComponent(AddBookbt)
                .addGap(34, 34, 34)
                .addComponent(BookDetailsbt)
                .addGap(34, 34, 34)
                .addComponent(IssueBookbt)
                .addGap(32, 32, 32)
                .addComponent(RetrunBookbt)
                .addGap(30, 30, 30)
                .addComponent(ShowDetailsbt)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Member Type:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Library No:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Branch :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Name :");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Std ID :");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Emp ID :");

        addbt.setText("Add Member");
        addbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtActionPerformed(evt);
            }
        });

        MemType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Value", "Student", "Faculty" }));
        MemType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MemTypeItemStateChanged(evt);
            }
        });
        MemType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemTypeActionPerformed(evt);
            }
        });

        branchtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Value", "CSE", "CAI", "AIML", "ECE", "ECT", "EEE", "CIVIL", "MECH", " " }));
        branchtype.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                branchtypeItemStateChanged(evt);
            }
        });
        branchtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchtypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(libno)
                            .addComponent(name)
                            .addComponent(sno)
                            .addComponent(empno)
                            .addComponent(MemType, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(branchtype, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(addbt)))
                .addContainerGap(324, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(libno, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MemType, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(branchtype, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sno, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empno, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addbt)
                .addGap(40, 40, 40))
        );

        jPanel3.setBackground(new java.awt.Color(102, 255, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/R.png"))); // NOI18N

        homebt.setText("Home");
        homebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(homebt)
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homebt)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddMembtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMembtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddMembtActionPerformed

    private void AddBookbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBookbtActionPerformed
        // TODO add your handling code here:
    AddBooks ab = new AddBooks();
    ab.setVisible(true); 
        
    }//GEN-LAST:event_AddBookbtActionPerformed

    private void BookDetailsbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookDetailsbtActionPerformed
        // TODO add your handling code here:
        BookDetails bd=new BookDetails();
        bd.setVisible(true);
    }//GEN-LAST:event_BookDetailsbtActionPerformed

    private void IssueBookbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssueBookbtActionPerformed
        // TODO add your handling code here:
         IssueBook ib=new IssueBook();
         ib.setVisible(true);
    }//GEN-LAST:event_IssueBookbtActionPerformed

    private void RetrunBookbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetrunBookbtActionPerformed
        // TODO add your handling code here:
            ReturnBook rb=new ReturnBook();
            rb.setVisible(true);
    }//GEN-LAST:event_RetrunBookbtActionPerformed

    private void ShowDetailsbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowDetailsbtActionPerformed
        // TODO add your handling code here:
         ShowDetails sd=new ShowDetails();
         sd.setVisible(true);
    }//GEN-LAST:event_ShowDetailsbtActionPerformed

    private void homebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtActionPerformed
        // TODO add your handling code here:
        Main m=new Main();
        m.setVisible(true);
    }//GEN-LAST:event_homebtActionPerformed

    private void MemTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MemTypeActionPerformed

    private void branchtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_branchtypeActionPerformed

    private void MemTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MemTypeItemStateChanged
        // TODO add your handling code here:
        String mem=MemType.getSelectedItem().toString();
        if(mem.equals("Student"))
        {
            sno.setEnabled(true);
            empno.setEnabled(false);
            empno.setText("");
        }
        else if(mem.equals("Faculty"))
        {
            sno.setEnabled(false);
            empno.setEnabled(true);
            sno.setText("");
        }
        else
        {
            sno.setEnabled(true);
            empno.setEnabled(true);
        }
    }//GEN-LAST:event_MemTypeItemStateChanged

    private void addbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtActionPerformed
        // TODO add your handling code here:
        if (name.getText().equals("")) {
        JOptionPane.showMessageDialog(this, "Please Fill Name");
        return;
    }

    if (sno.getText().equals("") && empno.getText().equals("")) {
        JOptionPane.showMessageDialog(this, "Please fill either SNO or EMPNO");
        return;
    }

    try {
        con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "scott", "tiger");
        pst = con.prepareStatement("INSERT INTO AddMem VALUES (?, ?, ?, ?, ?, ?)");
        pst.setString(1, libno.getText());
        pst.setString(2, String.valueOf(MemType.getSelectedItem()));
        pst.setString(3, String.valueOf(branchtype.getSelectedItem()));
        pst.setString(4, name.getText());
        pst.setString(5, sno.getText());
        pst.setString(6, empno.getText());

        int rc = pst.executeUpdate();
        if (rc == 1) {
            JOptionPane.showMessageDialog(this, "Member Added Successfully");
            
          
            libno.setText("");
            MemType.setSelectedIndex(0);
            branchtype.setSelectedIndex(0);
            name.setText("");
            sno.setText("");
            empno.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Adding Failed");
        }

       
       
        
    } catch (SQLException ex) {
        Logger.getLogger(AddMem.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage());
    }
        
    }//GEN-LAST:event_addbtActionPerformed

    private void branchtypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_branchtypeItemStateChanged
        // TODO add your handling code here:
        Loadlibraryno();
    }//GEN-LAST:event_branchtypeItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBookbt;
    private javax.swing.JButton AddMembt;
    private javax.swing.JButton BookDetailsbt;
    private javax.swing.JButton IssueBookbt;
    private javax.swing.JComboBox<String> MemType;
    private javax.swing.JButton RetrunBookbt;
    private javax.swing.JButton ShowDetailsbt;
    private javax.swing.JButton addbt;
    private javax.swing.JComboBox<String> branchtype;
    private javax.swing.JTextField empno;
    private javax.swing.JButton homebt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField libno;
    private javax.swing.JTextField name;
    private javax.swing.JTextField sno;
    // End of variables declaration//GEN-END:variables
 
}
