/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pullu
 */
public class BookDetails extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    DefaultTableModel model;

    /**
     * Creates new form BookDetails
     */
    public BookDetails() {
        initComponents();
        generateShowbook();
        loadbookdetails();

    }

    public void generateShowbook() {
        try {
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "scott", "tiger");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from book");
            Statement st1 = con.createStatement();
            ResultSet rs1 = st1.executeQuery("select * from bookdetails");
            
            if(rs1.next()==true)
            {
               while (rs.next()) {
                for (int i = 1; i <= rs.getInt(3); i++) {
                    String s = rs.getString(1).substring(0, 3) + rs.getString(2).substring(0, 3) + String.format("%03d", i).toUpperCase();
                    pst=con.prepareStatement("insert into bookdetails values(?,?,?)");
                    pst.setString(2,rs.getString(1));
                    pst.setString(3,rs.getString(2));
                    pst.setString(1,s);
                    pst.executeUpdate();
                }
            } 
            }

            
        } catch (SQLException ex) {
            Logger.getLogger(BookDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void loadbookdetails()
    {
        try {
           model=(DefaultTableModel)bookdetailstable.getModel();
           con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "scott", "tiger");
           Statement st=con.createStatement();
           model.setRowCount(0);
           ResultSet rs=st.executeQuery("select * from bookdetails");
           
           while(rs.next())
           {
               model.insertRow(model.getRowCount(),new Object[]{rs.getString(1),rs.getString(2),rs.getString(3)});
           }  
       } catch (SQLException ex) {
           Logger.getLogger(AddBooks.class.getName()).log(Level.SEVERE, null, ex);
       }
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        homebt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        AddMembt = new javax.swing.JButton();
        AddBookbt = new javax.swing.JButton();
        BookDetailsbt = new javax.swing.JButton();
        IssueBookbt = new javax.swing.JButton();
        RetrunBookbt = new javax.swing.JButton();
        ShowDetailsbt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookdetailstable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(102, 255, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/R.png"))); // NOI18N

        homebt.setText("Home");
        homebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(homebt)
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homebt)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        AddMembt.setText("Add Mem");
        AddMembt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddMembtActionPerformed(evt);
            }
        });

        AddBookbt.setText("Add Books");
        AddBookbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBookbtActionPerformed(evt);
            }
        });

        BookDetailsbt.setForeground(new java.awt.Color(255, 0, 0));
        BookDetailsbt.setText("Book Details");
        BookDetailsbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookDetailsbtActionPerformed(evt);
            }
        });

        IssueBookbt.setText("Issue Book");
        IssueBookbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssueBookbtActionPerformed(evt);
            }
        });

        RetrunBookbt.setText("Return Book");
        RetrunBookbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetrunBookbtActionPerformed(evt);
            }
        });

        ShowDetailsbt.setText("Show Details");
        ShowDetailsbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowDetailsbtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowDetailsbt)
                    .addComponent(RetrunBookbt)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(IssueBookbt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddBookbt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddMembt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BookDetailsbt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(AddMembt)
                .addGap(26, 26, 26)
                .addComponent(AddBookbt)
                .addGap(34, 34, 34)
                .addComponent(BookDetailsbt)
                .addGap(34, 34, 34)
                .addComponent(IssueBookbt)
                .addGap(32, 32, 32)
                .addComponent(RetrunBookbt)
                .addGap(30, 30, 30)
                .addComponent(ShowDetailsbt)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        bookdetailstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Book Name", "Author"
            }
        ));
        jScrollPane1.setViewportView(bookdetailstable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtActionPerformed
        // TODO add your handling code here:
        Main m = new Main();
        m.setVisible(true);
    }//GEN-LAST:event_homebtActionPerformed

    private void AddMembtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddMembtActionPerformed
        // TODO add your handling code here:
        AddMem am = new AddMem();
        am.setVisible(true);
    }//GEN-LAST:event_AddMembtActionPerformed

    private void AddBookbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBookbtActionPerformed
        // TODO add your handling code here:
        AddBooks ab = new AddBooks();
        ab.setVisible(true);

    }//GEN-LAST:event_AddBookbtActionPerformed

    private void BookDetailsbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookDetailsbtActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_BookDetailsbtActionPerformed

    private void IssueBookbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssueBookbtActionPerformed
        // TODO add your handling code here:
        IssueBook ib = new IssueBook();
        ib.setVisible(true);
    }//GEN-LAST:event_IssueBookbtActionPerformed

    private void RetrunBookbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetrunBookbtActionPerformed
        // TODO add your handling code here:
        ReturnBook rb = new ReturnBook();
        rb.setVisible(true);
    }//GEN-LAST:event_RetrunBookbtActionPerformed

    private void ShowDetailsbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowDetailsbtActionPerformed
        // TODO add your handling code here:
        ShowDetails sd = new ShowDetails();
        sd.setVisible(true);
    }//GEN-LAST:event_ShowDetailsbtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBookbt;
    private javax.swing.JButton AddMembt;
    private javax.swing.JButton BookDetailsbt;
    private javax.swing.JButton IssueBookbt;
    private javax.swing.JButton RetrunBookbt;
    private javax.swing.JButton ShowDetailsbt;
    private javax.swing.JTable bookdetailstable;
    private javax.swing.JButton homebt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
