/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

/**
 *
 * @author pullu
 */
public class Main extends javax.swing.JFrame {
 

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        addmembt = new javax.swing.JButton();
        addbookbt = new javax.swing.JButton();
        bookdetailsbt = new javax.swing.JButton();
        issuebookbt = new javax.swing.JButton();
        returnbookbt = new javax.swing.JButton();
        showdetailsbt = new javax.swing.JButton();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        hombt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 204));

        jDesktopPane1.setBackground(new java.awt.Color(0, 0, 153));

        addmembt.setText("Add Mem");
        addmembt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmembtActionPerformed(evt);
            }
        });

        addbookbt.setText("Add Book");
        addbookbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbookbtActionPerformed(evt);
            }
        });

        bookdetailsbt.setText("Book Details");
        bookdetailsbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookdetailsbtActionPerformed(evt);
            }
        });

        issuebookbt.setText("Issue Book");
        issuebookbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuebookbtActionPerformed(evt);
            }
        });

        returnbookbt.setText("Retun Book");
        returnbookbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnbookbtActionPerformed(evt);
            }
        });

        showdetailsbt.setText("Show Details");
        showdetailsbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showdetailsbtActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(addmembt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(addbookbt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bookdetailsbt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(issuebookbt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(returnbookbt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(showdetailsbt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showdetailsbt)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(issuebookbt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addmembt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addbookbt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bookdetailsbt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(returnbookbt))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addmembt)
                .addGap(18, 18, 18)
                .addComponent(addbookbt)
                .addGap(33, 33, 33)
                .addComponent(bookdetailsbt)
                .addGap(18, 18, 18)
                .addComponent(issuebookbt)
                .addGap(34, 34, 34)
                .addComponent(returnbookbt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(showdetailsbt)
                .addGap(28, 28, 28))
        );

        jDesktopPane3.setBackground(new java.awt.Color(0, 255, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/R.png"))); // NOI18N

        hombt.setText("Home");
        hombt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hombtActionPerformed(evt);
            }
        });

        jDesktopPane3.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(hombt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hombt)
                .addGap(23, 23, 23))
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hombt)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(739, Short.MAX_VALUE))
            .addComponent(jDesktopPane3)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showdetailsbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showdetailsbtActionPerformed
        // TODO add your handling code here:
       ShowDetails sd=new ShowDetails();
         sd.setVisible(true);
    }//GEN-LAST:event_showdetailsbtActionPerformed

    private void returnbookbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnbookbtActionPerformed
        // TODO add your handling code here:
        ReturnBook rb=new ReturnBook();
            rb.setVisible(true);
    }//GEN-LAST:event_returnbookbtActionPerformed

    private void issuebookbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuebookbtActionPerformed
        // TODO add your handling code here:
       IssueBook ib=new IssueBook();
         ib.setVisible(true);
    }//GEN-LAST:event_issuebookbtActionPerformed

    private void bookdetailsbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookdetailsbtActionPerformed
        // TODO add your handling code here:
      BookDetails bd=new BookDetails();
        bd.setVisible(true);
    }//GEN-LAST:event_bookdetailsbtActionPerformed

    private void addbookbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbookbtActionPerformed
        // TODO add your handling code here:
     AddBooks ab = new AddBooks();
    ab.setVisible(true); 
    }//GEN-LAST:event_addbookbtActionPerformed

    private void addmembtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmembtActionPerformed
        // TODO add your handling code here:
      AddMem am=new AddMem();
        am.setVisible(true);
    }//GEN-LAST:event_addmembtActionPerformed

    private void hombtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hombtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_hombtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbookbt;
    private javax.swing.JButton addmembt;
    private javax.swing.JButton bookdetailsbt;
    private javax.swing.JButton hombt;
    private javax.swing.JButton issuebookbt;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton returnbookbt;
    private javax.swing.JButton showdetailsbt;
    // End of variables declaration//GEN-END:variables

    
}
